<?php
        /*Config file*/

$ic_default_ad_size = "300x250";

$ic_ad_tag_url = "http://ads.investingchannel.com/adtags";

$ic_default_target="ros";

$ic_targets =   array(
  'advertiser','
  alternativeinvesting','
  bonds','
  buyside','
  buyside_hedgefundmanagers','
  buyside_mutualfundmanagers','
  buyside_pensionfundmanangers','
  buyside_proprietarytrading','
  careers','
  careers_investingandfinance','
  careers_noninvesting','
  commodities','
  developedmarkets','
  developedmarkets_commentary','
  developedmarkets_news','
  developedmarkets_research','
  dividends','
  splits','
  economics','
  education','
  emergingmarkets','
  emergingmarkets_commentary','
  emergingmarkets_news','
  emergingmarkets_research','
  energy','
  equities','
  etf','
  financialadvisor','
  forex','
  fundamentalanalysis','
  futures','
  greeninvesting','
  home','
  largecap','
  mutualfund','
  non-finance','
  non-finance_automotive','
  non-finance_b2b','
  non-finance_biotech','
  non-finance_entertainment','
  non-finance_environmental','
  non-finance_governmentandpolitics','
  non-finance_healthcare','
  non-finance_lifestyle','
  non-finance_smallbusiness','
  non-finance_sports','
  non-finance_technology','
  non-finance_travel','
  options','
  otcpinksheets','
  personalfinance','
  portfoliogaming','
  privateequity','
  quantitativetrading','
  quotepages','
  research','
  ros','
  sellside','
  smallcap','
  software','
  software_investing','
  software_noninvesting','
  technicalanalysis','
  valueinvesting','
  venturecapital');
?>